version: '3.8'

services:
  checkup:
    build: .
    container_name: checkup
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Persist database and configuration
      - checkup_data:/app/data
      # Mount Docker socket for Docker monitoring (optional)
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount custom config file (optional)
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/checkup.db
      # Override these in your .env file
      - JWT_SECRET=change-this-secret-key-in-production
      - PORT=3000
    networks:
      - checkup_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Gotify for notifications
  gotify:
    image: gotify/server:latest
    container_name: checkup_gotify
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - gotify_data:/app/data
    environment:
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=admin
    networks:
      - checkup_network
    profiles:
      - gotify

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: checkup_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - checkup
    networks:
      - checkup_network
    profiles:
      - nginx

volumes:
  checkup_data:
    driver: local
  gotify_data:
    driver: local

networks:
  checkup_network:
    driver: bridge